### ISSUE TITLE
Responsiveness in event section

### ISSUE THREAD

**Issue by the-macson** [CodingNinjas-LPU/Official_website#31]
![Screenshot (33)](https://user-images.githubusercontent.com/71259159/152697146-a8c71150-ed70-4232-80de-d871cc9c486a.png)

**Comment by syket-das** [comment]
===========================Fixed===========================
Hope it will work now
![Techsahead-💻](https://user-images.githubusercontent.com/80612737/152749993-7c969d72-4a22-4aa2-94dd-f2c758cebf4a.png)

**Comment by the-macson** [comment]
yaa now it's working fine. but still footer are not correct of this page like social media icons and no space of left side of logo.
