### ISSUE TITLE
space between about and footer section and alignment of social media icon and alignment of visit 

### ISSUE THREAD

**Issue by the-macson** [CodingNinjas-LPU/Official_website#38]
![Screenshot (47)](https://user-images.githubusercontent.com/71259159/152697435-02884727-d4e7-49d0-addf-fdcdb0bbdbc3.png)

**Comment by syket-das** [comment]
-----------------------------------------------------------fixed---------------------------------------------------------------------
![Document](https://user-images.githubusercontent.com/80612737/152749212-a9f69de6-bab1-4db8-8e7f-ff71f7648353.png)

**Comment by the-macson** [comment]
In screen shot it's not looks like it is fixed. Can you check again ?

**Comment by syket-das** [comment]
can you be more specific

**Comment by the-macson** [comment]
alignment of social media icons and there is no space in left side of logo in footer

**Comment by syket-das** [comment]
got you @the-macson
